name: build
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 16 * * *'
jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable
    - run: |
        cd flake
        nix flake update
        cd ..
    - run: |
        git config --local user.email "3264117476@qq.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git commit -m "Update flakes" || true
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
